### Create a book
POST https://<YOUR-APP>.azurewebsites.net/addressbooks
Content-Type: application/json

{"label": "My Contacts"}

### Add buddy 1
POST https://<YOUR-APP>.azurewebsites.net/addressbooks/1/buddies
Content-Type: application/json

{"name": "Anas", "phoneNumber": "613-2222"}

### Add buddy 2
POST https://<YOUR-APP>.azurewebsites.net/addressbooks/1/buddies
Content-Type: application/json

{"name": "Ayoubi", "phoneNumber": "613-1111"}

### (Optional) check JSON
GET https://<YOUR-APP>.azurewebsites.net/addressbooks/1
