name: Build and deploy JAR app to Azure Web App - anas-addressbook-app

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write  # harmless; useful if you later open PRs

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run tests
        run: mvn -B -ntp -DskipTests=false test

      - name: Publish JUnit report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Results
          path: target/surefire-reports/*.xml
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}   # explicit token (optional)
